"""use string in users.id

Revision ID: a286921e954c
Revises: 
Create Date: 2024-05-07 10:27:51.905688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a286921e954c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    op.create_table('masterProduct',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('title', sa.VARCHAR(length=100), nullable=True),
        sa.Column('url', sa.VARCHAR(length=100), nullable=True),
        sa.Column('description', sa.VARCHAR(length=100), nullable=True),
        sa.Column('features', sa.VARCHAR(length=100), nullable=True),
        sa.Column('content', sa.VARCHAR(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True)
    )
    
    op.create_table('localMaster',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('title', sa.VARCHAR(length=100), nullable=True),
        sa.Column('marketName', sa.VARCHAR(length=100), nullable=True),
        sa.Column('marketId', sa.Integer(), nullable=False),
        sa.Column('settings', sa.VARCHAR(length=100), nullable=True),
        sa.Column('prompt', sa.VARCHAR(length=100), nullable=True),
        sa.Column('content', sa.VARCHAR(length=100), nullable=True),
        sa.Column('masterProductId', sa.Integer(), sa.ForeignKey('masterProduct.id'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True)
    )
    
    op.create_table('distributorVersion',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('title', sa.VARCHAR(length=100), nullable=True),
        sa.Column('distributor', sa.VARCHAR(length=100), nullable=True),
        sa.Column('distributorId', sa.Integer(), nullable=False),
        sa.Column('settings', sa.VARCHAR(length=100), nullable=True),
        sa.Column('prompt', sa.VARCHAR(length=100), nullable=True),
        sa.Column('content', sa.VARCHAR(length=100), nullable=True),
        sa.Column('localMasterId', sa.Integer(), sa.ForeignKey('localMaster.id'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True)
    )
    
    op.create_table('distributor',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('title', sa.VARCHAR(length=100), nullable=True),
        sa.Column('label', sa.VARCHAR(length=100), nullable=True),
        sa.Column('description', sa.VARCHAR(length=100), nullable=True),
        sa.Column('defaultSettings', sa.VARCHAR(length=100), nullable=True),
        sa.Column('tone', sa.VARCHAR(length=100), nullable=True),
        sa.Column('format', sa.VARCHAR(length=100), nullable=True),
        sa.Column('seoKeywords', sa.VARCHAR(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('distributorVersionId', sa.Integer(), sa.ForeignKey('distributorVersion.id'), nullable=True)
    )
    
    op.create_table('market',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('title', sa.VARCHAR(length=100), nullable=True),
        sa.Column('defaultSettings', sa.VARCHAR(length=100), nullable=True),
        sa.Column('defaultAxis', sa.VARCHAR(length=100), nullable=True),
        sa.Column('languages', sa.VARCHAR(length=100), nullable=True),
        sa.Column('culturalTrends', sa.VARCHAR(length=100), nullable=True),
        sa.Column('seoKeywords', sa.VARCHAR(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('localMasterId', sa.Integer(), sa.ForeignKey('localMaster.id'), nullable=True)
    )

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distributor')
    op.drop_table('masterProduct')
    op.drop_table('market')
    op.drop_table('localMaster')
    op.drop_table('distributorVersion')
    # ### end Alembic commands ###


